# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'

target 'CookedBooked' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CookedBooked


pod 'Parse' 
pod 'ParseSwift'
pod 'AlamofireImage', '~> 4.1'
pod 'Alamofire'

end
